package de.greenrobot.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AD_VER_INFO".
 */
public class AdVerInfo {

    private Long id;
    private int adNumber;
    /** Not-null value. */
    private String soureName;
    /** Not-null value. */
    private String pathUrl;
    /** Not-null value. */
    private String soureType;
    private int playTime;
    private int status;
    private String fileDir;
    private String fileName;

    public AdVerInfo() {
    }

    public AdVerInfo(Long id) {
        this.id = id;
    }

    public AdVerInfo(Long id, int adNumber, String soureName, String pathUrl, String soureType, int playTime, int status, String fileDir, String fileName) {
        this.id = id;
        this.adNumber = adNumber;
        this.soureName = soureName;
        this.pathUrl = pathUrl;
        this.soureType = soureType;
        this.playTime = playTime;
        this.status = status;
        this.fileDir = fileDir;
        this.fileName = fileName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getAdNumber() {
        return adNumber;
    }

    public void setAdNumber(int adNumber) {
        this.adNumber = adNumber;
    }

    /** Not-null value. */
    public String getSoureName() {
        return soureName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSoureName(String soureName) {
        this.soureName = soureName;
    }

    /** Not-null value. */
    public String getPathUrl() {
        return pathUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPathUrl(String pathUrl) {
        this.pathUrl = pathUrl;
    }

    /** Not-null value. */
    public String getSoureType() {
        return soureType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSoureType(String soureType) {
        this.soureType = soureType;
    }

    public int getPlayTime() {
        return playTime;
    }

    public void setPlayTime(int playTime) {
        this.playTime = playTime;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getFileDir() {
        return fileDir;
    }

    public void setFileDir(String fileDir) {
        this.fileDir = fileDir;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

}
