package de.greenrobot.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COMMODITY_INFO".
 */
public class CommodityInfo {

    private Long id;
    /** Not-null value. */
    private String goodsCode;
    private Integer goodsSerial;
    private int commType;
    /** Not-null value. */
    private String name;
    private Integer price;
    private String imgPath;

    public CommodityInfo() {
    }

    public CommodityInfo(Long id) {
        this.id = id;
    }

    public CommodityInfo(Long id, String goodsCode, Integer goodsSerial, int commType, String name, Integer price, String imgPath) {
        this.id = id;
        this.goodsCode = goodsCode;
        this.goodsSerial = goodsSerial;
        this.commType = commType;
        this.name = name;
        this.price = price;
        this.imgPath = imgPath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getGoodsCode() {
        return goodsCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode;
    }

    public Integer getGoodsSerial() {
        return goodsSerial;
    }

    public void setGoodsSerial(Integer goodsSerial) {
        this.goodsSerial = goodsSerial;
    }

    public Integer getCommType() {
        return commType;
    }

    public void setCommType(Integer commType) {
        this.commType = commType;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public String getImgPath() {
        return imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

}
