package de.greenrobot.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.greendao.KeyInfo;
import de.greenrobot.greendao.CommodityInfo;
import de.greenrobot.greendao.GoodsInfo;
import de.greenrobot.greendao.SetTimeInfo;
import de.greenrobot.greendao.SetOpenDoor;
import de.greenrobot.greendao.OrdersInfo;
import de.greenrobot.greendao.AdVerInfo;

import de.greenrobot.greendao.KeyInfoDao;
import de.greenrobot.greendao.CommodityInfoDao;
import de.greenrobot.greendao.GoodsInfoDao;
import de.greenrobot.greendao.SetTimeInfoDao;
import de.greenrobot.greendao.SetOpenDoorDao;
import de.greenrobot.greendao.OrdersInfoDao;
import de.greenrobot.greendao.AdVerInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig keyInfoDaoConfig;
    private final DaoConfig commodityInfoDaoConfig;
    private final DaoConfig goodsInfoDaoConfig;
    private final DaoConfig setTimeInfoDaoConfig;
    private final DaoConfig setOpenDoorDaoConfig;
    private final DaoConfig ordersInfoDaoConfig;
    private final DaoConfig adVerInfoDaoConfig;

    private final KeyInfoDao keyInfoDao;
    private final CommodityInfoDao commodityInfoDao;
    private final GoodsInfoDao goodsInfoDao;
    private final SetTimeInfoDao setTimeInfoDao;
    private final SetOpenDoorDao setOpenDoorDao;
    private final OrdersInfoDao ordersInfoDao;
    private final AdVerInfoDao adVerInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        keyInfoDaoConfig = daoConfigMap.get(KeyInfoDao.class).clone();
        keyInfoDaoConfig.initIdentityScope(type);

        commodityInfoDaoConfig = daoConfigMap.get(CommodityInfoDao.class).clone();
        commodityInfoDaoConfig.initIdentityScope(type);

        goodsInfoDaoConfig = daoConfigMap.get(GoodsInfoDao.class).clone();
        goodsInfoDaoConfig.initIdentityScope(type);

        setTimeInfoDaoConfig = daoConfigMap.get(SetTimeInfoDao.class).clone();
        setTimeInfoDaoConfig.initIdentityScope(type);

        setOpenDoorDaoConfig = daoConfigMap.get(SetOpenDoorDao.class).clone();
        setOpenDoorDaoConfig.initIdentityScope(type);

        ordersInfoDaoConfig = daoConfigMap.get(OrdersInfoDao.class).clone();
        ordersInfoDaoConfig.initIdentityScope(type);

        adVerInfoDaoConfig = daoConfigMap.get(AdVerInfoDao.class).clone();
        adVerInfoDaoConfig.initIdentityScope(type);

        keyInfoDao = new KeyInfoDao(keyInfoDaoConfig, this);
        commodityInfoDao = new CommodityInfoDao(commodityInfoDaoConfig, this);
        goodsInfoDao = new GoodsInfoDao(goodsInfoDaoConfig, this);
        setTimeInfoDao = new SetTimeInfoDao(setTimeInfoDaoConfig, this);
        setOpenDoorDao = new SetOpenDoorDao(setOpenDoorDaoConfig, this);
        ordersInfoDao = new OrdersInfoDao(ordersInfoDaoConfig, this);
        adVerInfoDao = new AdVerInfoDao(adVerInfoDaoConfig, this);

        registerDao(KeyInfo.class, keyInfoDao);
        registerDao(CommodityInfo.class, commodityInfoDao);
        registerDao(GoodsInfo.class, goodsInfoDao);
        registerDao(SetTimeInfo.class, setTimeInfoDao);
        registerDao(SetOpenDoor.class, setOpenDoorDao);
        registerDao(OrdersInfo.class, ordersInfoDao);
        registerDao(AdVerInfo.class, adVerInfoDao);
    }
    
    public void clear() {
        keyInfoDaoConfig.getIdentityScope().clear();
        commodityInfoDaoConfig.getIdentityScope().clear();
        goodsInfoDaoConfig.getIdentityScope().clear();
        setTimeInfoDaoConfig.getIdentityScope().clear();
        setOpenDoorDaoConfig.getIdentityScope().clear();
        ordersInfoDaoConfig.getIdentityScope().clear();
        adVerInfoDaoConfig.getIdentityScope().clear();
    }

    public KeyInfoDao getKeyInfoDao() {
        return keyInfoDao;
    }

    public CommodityInfoDao getCommodityInfoDao() {
        return commodityInfoDao;
    }

    public GoodsInfoDao getGoodsInfoDao() {
        return goodsInfoDao;
    }

    public SetTimeInfoDao getSetTimeInfoDao() {
        return setTimeInfoDao;
    }

    public SetOpenDoorDao getSetOpenDoorDao() {
        return setOpenDoorDao;
    }

    public OrdersInfoDao getOrdersInfoDao() {
        return ordersInfoDao;
    }

    public AdVerInfoDao getAdVerInfoDao() {
        return adVerInfoDao;
    }

}
