package de.greenrobot.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ORDERS_INFO".
 */
public class OrdersInfo {

    private Long id;
    /** Not-null value. */
    private String orderNum;
    private int totalNum;
    private int totalPrice;
    private int goodsID;
    /** Not-null value. */
    private String goodsCode;
    /** Not-null value. */
    private String goodsName;
    private int payType;
    private int orderStatus;
    private int syncStatuc;
    /** Not-null value. */
    private String time;

    public OrdersInfo() {
    }

    public OrdersInfo(Long id) {
        this.id = id;
    }

    public OrdersInfo(Long id, String orderNum, int totalNum, int totalPrice, int goodsID, String goodsCode, String goodsName, int payType, int orderStatus, int syncStatuc, String time) {
        this.id = id;
        this.orderNum = orderNum;
        this.totalNum = totalNum;
        this.totalPrice = totalPrice;
        this.goodsID = goodsID;
        this.goodsCode = goodsCode;
        this.goodsName = goodsName;
        this.payType = payType;
        this.orderStatus = orderStatus;
        this.syncStatuc = syncStatuc;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOrderNum() {
        return orderNum;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    public int getTotalNum() {
        return totalNum;
    }

    public void setTotalNum(int totalNum) {
        this.totalNum = totalNum;
    }

    public int getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(int totalPrice) {
        this.totalPrice = totalPrice;
    }

    public int getGoodsID() {
        return goodsID;
    }

    public void setGoodsID(int goodsID) {
        this.goodsID = goodsID;
    }

    /** Not-null value. */
    public String getGoodsCode() {
        return goodsCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode;
    }

    /** Not-null value. */
    public String getGoodsName() {
        return goodsName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    public int getPayType() {
        return payType;
    }

    public void setPayType(int payType) {
        this.payType = payType;
    }

    public int getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(int orderStatus) {
        this.orderStatus = orderStatus;
    }

    public int getSyncStatuc() {
        return syncStatuc;
    }

    public void setSyncStatuc(int syncStatuc) {
        this.syncStatuc = syncStatuc;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

}
