package de.greenrobot.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SET_OPEN_DOOR".
 */
public class SetOpenDoor {

    private Long id;
    private String openTime;
    private Integer OrderId;
    private Integer syncStatuc;

    public SetOpenDoor() {
    }

    public SetOpenDoor(Long id) {
        this.id = id;
    }

    public SetOpenDoor(Long id, String openTime, Integer OrderId, Integer syncStatuc) {
        this.id = id;
        this.openTime = openTime;
        this.OrderId = OrderId;
        this.syncStatuc = syncStatuc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOpenTime() {
        return openTime;
    }

    public void setOpenTime(String openTime) {
        this.openTime = openTime;
    }

    public Integer getOrderId() {
        return OrderId;
    }

    public void setOrderId(Integer OrderId) {
        this.OrderId = OrderId;
    }

    public Integer getSyncStatuc() {
        return syncStatuc;
    }

    public void setSyncStatuc(Integer syncStatuc) {
        this.syncStatuc = syncStatuc;
    }

}
